language: php
sudo: false
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - hhvm
before_install:
    - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.1-bin.tar.gz
    - tar -xzvf apache-ant-1.10.1-bin.tar.gz
    - export PATH=`pwd`/apache-ant-1.10.1/bin:$PATH
    - echo $(ant -version)
    - composer install
script:
    - vendor/bin/phpunit
    - ant
